language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
services:
  - mongodb
env:
  global:
    - NODE_ENV=travisci
    - BUILD_DIR=`pwd`/shea-ymc
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - ls $BUILD_DIR/thoughtsome/app/bower_components
